build:
	g++ -std=c++14 -I${VULKAN_SDK}/include/vulkan -I/home/adrian/venginenative/VEngine -L/home/adrian/venginenative/VEngine `find . | grep ".*.cpp"` -ldl -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lXcursor -lXinerama -lvengine -lglfw3 -lvulkan
